server:
  port: 8080

spring:
  datasource:
    username: root
    password: Jk@
    url: jdbc:mysql://localhost:3306/userservice
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: update
    show-sql: true