spring.application.name=day2
spring.datasource.username = root
spring.datasource.password = Jk@93372
spring.datasource.url =jdbc:mysql://localhost:3306/mca
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.AtomikosJtaPlatform